[package]
name = "lightning-rapid-gossip-sync"
<<<<<<< HEAD
version = "0.0.113"
=======
version = "0.0.114"
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
authors = ["Arik Sosman <git@arik.io>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning"
edition = "2018"
description = """
Utility to process gossip routing data from Rapid Gossip Sync Server.
"""

[features]
default = ["std"]
no-std = ["lightning/no-std"]
std = ["lightning/std"]
_bench_unstable = []

[dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning", default-features = false }
bitcoin = { version = "0.29.0", default-features = false }

[dev-dependencies]
lightning = { version = "0.0.113", path = "../lightning", features = ["_test_utils"] }
=======
lightning = { version = "0.0.114", path = "../lightning", default-features = false }
bitcoin = { version = "0.29.0", default-features = false }

[dev-dependencies]
lightning = { version = "0.0.114", path = "../lightning", features = ["_test_utils"] }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
