[package]
name = "lightning-invoice"
description = "Data structures to parse and serialize BOLT11 lightning invoices"
<<<<<<< HEAD
version = "0.21.0"
=======
version = "0.22.0"
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]
documentation = "https://docs.rs/lightning-invoice/"
license = "MIT OR Apache-2.0"
keywords = [ "lightning", "bitcoin", "invoice", "BOLT11" ]
readme = "README.md"
repository = "https://github.com/lightningdevkit/rust-lightning/"
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std"]
no-std = ["hashbrown", "lightning/no-std"]
std = ["bitcoin_hashes/std", "num-traits/std", "lightning/std", "bech32/std"]

[dependencies]
bech32 = { version = "0.9.0", default-features = false }
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning", default-features = false }
=======
lightning = { version = "0.0.114", path = "../lightning", default-features = false }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
secp256k1 = { version = "0.24.0", default-features = false, features = ["recovery", "alloc"] }
num-traits = { version = "0.2.8", default-features = false }
bitcoin_hashes = { version = "0.11", default-features = false }
hashbrown = { version = "0.8", optional = true }
serde = { version = "1.0.118", optional = true }

[dev-dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning", default-features = false, features = ["_test_utils"] }
=======
lightning = { version = "0.0.114", path = "../lightning", default-features = false, features = ["_test_utils"] }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
hex = "0.4"
serde_json = { version = "1"}
