[package]
name = "lightning-net-tokio"
<<<<<<< HEAD
version = "0.0.113"
=======
version = "0.0.114"
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
authors = ["Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Implementation of the rust-lightning network stack using Tokio.
For Rust-Lightning clients which wish to make direct connections to Lightning P2P nodes, this is a simple alternative to implementing the required network stack, especially for those already using Tokio.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcoin = "0.29.0"
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning" }
=======
lightning = { version = "0.0.114", path = "../lightning" }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
tokio = { version = "1.0", features = [ "io-util", "macros", "rt", "sync", "net", "time" ] }

[dev-dependencies]
tokio = { version = "1.14", features = [ "io-util", "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
lightning = { version = "0.0.114", path = "../lightning", features = ["_test_utils"] }
