[package]
name = "lightning-persister"
<<<<<<< HEAD
version = "0.0.113"
=======
version = "0.0.114"
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
authors = ["Valentine Wallace", "Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Utilities to manage Rust-Lightning channel data persistence and retrieval.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
_bench_unstable = ["lightning/_bench_unstable"]

[dependencies]
bitcoin = "0.29.0"
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning" }
=======
lightning = { version = "0.0.114", path = "../lightning" }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase"] }

[dev-dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.113", path = "../lightning", features = ["_test_utils"] }
=======
lightning = { version = "0.0.114", path = "../lightning", features = ["_test_utils"] }
>>>>>>> 3d479c9de62665214e8589699cdbb8a797b77188
